### ISSUE TITLE
cadence-proxy panics and CadenceClient fails to connect when run from a net5.0 project which also references Microsoft.Extensions.* 5.0.0 packages

### ISSUE THREAD

**Issue by avalesano** [nforgeio/neonKUBE#1199] opened 2021-05-26 22:45 UTC
Lately, my team has run into some strange issues where CadenceClient is unable to successfully connect to the Cadence Server.  This only seems to happen when running in a net5.0 project, while also referencing certain Microsoft.Extensions.* nuget packages at version 5.0.0.  Once these packages are downgraded back to 3.1.15, everything starts working again.

The error usually takes the form of an HttpRequestException:
```
fail: bug_repro_5_0_0_fail.ExampleWorker[0]
      Error: No connection could be made because the target machine actively refused it. (127.0.0.1:56809)
fail: bug_repro_5_0_0_fail.ExampleWorker[0]
         at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
         at Neon.Cadence.CadenceExtensions.SendRequestAsync[TRequest](HttpClient client, TRequest request)
         at Neon.Cadence.CadenceClient.CallProxyAsync(ProxyRequest request, TimeSpan timeout, CancellationToken cancellationToken)
         at Neon.Cadence.WorkflowBase.RegisterAsync(CadenceClient client, Type workflowType, String workflowTypeName, String domain)
         at Neon.Cadence.CadenceClient.RegisterAssemblyWorkflowsAsync(Assembly assembly, String domain)
         at Neon.Cadence.CadenceClient.RegisterAssemblyAsync(Assembly assembly, String domain)
         at bug_repro_5_0_0_fail.ExampleWorker.ExecuteAsync(CancellationToken stoppingToken) in C:\code\Neon.cadence-proxy-bug-repro\bug_repro_5_0_0_fail\ExampleWorker.cs:line 40
```

Digging a little bit deeper, it appears that this happens because cadence-proxy.exe crashes nearly immediately after it starts, so there is nothing for CadenceClient to connect to.  By setting the flags     `"Debug": true, "LogLevel": "Debug", "DebugPrelaunched": true` in CadenceSettings and running cadence-proxy.exe externally (so the log output can be captured), I'm seeing this error message:
```
$ ./cadence-proxy.exe
May 26 17:08:48 INFO    server          Server Details  {"Address": "127.0.0.1:5000", "ProcessId": 18672}
May 26 17:09:08 INFO    init            InitializeRequest Received      {"ClientId": 1, "RequestId": 1, "ProcessId": 18672}
May 26 17:09:08 INFO    cadence-proxy   Initialization info     {"Reply Address": "http://127.0.0.1:5001/", "LogLevel": "Debug"}
panic: Put http://127.0.0.1:5001/: EOF

goroutine 23 [running]:
github.com/cadence-proxy/internal/endpoints.sendMessage(0xfdf920, 0xc0002e0028)
        C:/src/neonKUBE/Go/src/github.com/cadence-proxy/internal/endpoints/utils.go:151 +0xb6
created by github.com/cadence-proxy/internal/endpoints.sendLogRequest
        C:/src/neonKUBE/Go/src/github.com/cadence-proxy/internal/endpoints/logger.go:146 +0x559
```

Overall this seems very strange that referencing a package in the containing project could somehow cause errors in another dependency, much less in a separately compiled program written in a different language (cadence-proxy).  But I've been able to isolate it down to just Neon.Cadence and the Microsoft.Extensions.Hosting nuget package.  Using the same exact code, everything works fine with version 3.1.15, and fails with 5.0.0.  I've created an example solution here: https://github.com/avalesano/Neon.cadence-proxy-bug-repro

This seems very similar to https://github.com/nforgeio/neonKUBE/issues/1162, except in reverse.  Rather than Neon itself containing the reference, it's the parent net5.0 project.

**Comment by jefflill** [comment] 2021-05-27 00:47
It looks like MSFT broke their .NET Standard promise: https://github.com/dotnet/aspnetcore/issues/28098

We're not entirely sure what to do about this: it seems like a big mess.  It seems like MSFT thinks that everybody will immediately move to .NET5.0 and drop NET Standard 2.0 at the same time.  I suppose that we could multi-target our libraries to NET Standard 2.0 and .NET 5.0 but that seems like more work than we want to do.

Alternatively, we could drop support for NET Standard 2.0 and .NET Core entirely and go all-in on .NET 5.0.

**Comment by jefflill** [comment] 2021-05-27 00:59
One thing we could try is upgrading to the latest 5.x extensions and other packages in the hope that there's been some fixes.  It appears that this is supposed to work but MSFT isn't testing combinations of packages.

**Comment by jefflill** [comment] 2021-06-05 04:26
I've tried multi-targeting the Cadence and Temporal libraries for **netcoreapp3.1**, **netstandard2.0** and **net5.0** as well as multi-targeting the test projects without success, figuring that the .NET SDKs would handle any dependencies like this.  I haven't used multi-targeting much before and I do like it and have done the same for other library and test projects.

I verified that each target test project is consuming the correct version of the Cadence and Temporal assemblies.,

I also installed the latest .NET SDKs: **3.1.409** and **5.0.300** thinking there might have been some fixes but this didn't help either.

My next idea is that perhaps the problem is the fact that both the Cadence and Temporal libraries import:

- Microsoft.AspNetCore.Server.Kestrel
- Microsoft.Net.Http.Server

Where **Kestrel** is used to implement the HTTP server used by the proxies to send requests/replies to the client for .NET Core/5.0 and the **Microsoft.Net.Http.Server** is used when running on .NET Framework.  Perhaps this is causing the conflict.

The idea is to add a **net48** target to both the Cadence/Temporal projects and then reference only **Microsoft.Net.Http.Server** only for net48 and reference Kestrel for the other targets.

I'll have another look at this tomorrow evening, if I'm not too wiped out after helping mom do yard work.

**Comment by jefflill** [comment] 2021-06-07 21:19
This looks like it's fixed now and I've release neonLIBRARY v2.15.0 with the changes:

https://github.com/nforgeio/neonKUBE/releases/tag/neonLIBRARY-v2.15.0

**Comment by jefflill** [comment] 2021-10-29 20:02
@johncburns1: So the new `HTTPListener` from the EmbedIO nuget package is working better for both Cadence and Temporal but the tests seem to crap out after running a while.  I'm eventually seeing a socket closed exception when transmitting a request to the proxy.

This is easy to replicate by running the **Base_PingAttack** Cadence unit test.

I wonder if you could have a look on the GOLANG side and see if you're seeing any errors trying to communicate back to the client.  I'm starting to wonder whether we should communicate another way, perhaps via raw sockets or something.  The nice thing about this is that we could make the semantics of a new method match what we'll eventually be doing for the shared library/in-memory communication.

Another alternative would be to just do the shared library change now and call it a day.  The only problem is that we'd lose debug mode and the ability the debug the GOLANG code.

**Comment by jefflill** [comment] 2021-10-30 17:33
So this appears to be a problem on the proxy side:
```
bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.
```
![image](https://user-images.githubusercontent.com/4908431/139543196-0e80ff03-748e-4061-bc8a-b071bd8e2eb0.png)

I've verified that the client side web server is still handling requests after this the proxy panic.

**Comment by jefflill** [comment] 2021-10-30 17:51
OK, it looks like the new server is having the client close every connection.  I'll see if there's a way to disable this:
![image](https://user-images.githubusercontent.com/4908431/139543779-b30b1700-ecf6-4be7-9a09-a735f9af16cd.png)

**Comment by jefflill** [comment] 2021-10-30 18:35
@johncburns1 and I have decided that it's time convert the proxies into shared libraries: #1295

**Closed by jefflill** 2021-10-30 18:35 UTC
