### ISSUE TITLE
neon run file permissions

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#517] opened 2019-05-08 20:10 UTC
I couldn't use the neon run command to load in a docker cert because of the permissions. 

Loading key from "C:\Users\Marcus Bowyer\.neonkube\temp\4be87109-a074-47b3-ab9d-7e67c8a9dd0a.tmp"...
refusing to load key from C:\Users\Marcus Bowyer\.neonkube\temp\4be87109-a074-47b3-ab9d-7e67c8a9dd0a.tmp: private key file C:\Users\Marcus Bowyer\.neonkube\temp\4be87109-a074-47b3-ab9d-7e67c8a9dd0a.tmp must not be readable or writable by others

**Comment by marcusbooyah** [comment] 2019-05-09 19:24
This is related: https://github.com/docker/cli/issues/1696

**Comment by jefflill** [comment] 2019-05-11 20:52
@marcusbooyah: Can you please add some details above so I can reproduce this and then assign this to me?

I'll bet the problem is due to the `neon` decrypting files to an encrypted temporary directory in an effort to reduce the possibly of leaking secrets and then Docker is unable to mount and read these files because it's not actually running locally and Windows file sharing won't be able to decrypt the file.

**Comment by marcusbooyah** [comment] 2019-05-11 20:57
I don't think this is a neon issue, see the thread in the comment above. I tried creating a docker cert, then immediately loading it in again, and I still saw the error.

**Comment by jefflill** [comment] 2019-05-11 22:28
Actually, I’m pretty sure that’s the problem.  The /Users/USER/.neonkube directory is encrypted and I’ll bet that Docker is using a Windows file share to load the cert into its VM.

I’ll add an option to neon that doesn’t use the temp directory within .neonkube and we can see if that helps.

**Comment by jefflill** [comment] 2019-05-12 15:43
After our phone conversation, I'm convinced this is issue is not caused by **neon-cli** but I do believe there could be scenarios where disabling use of the encrypted user folder could be important like mounting a decrypted file to a Docker container.  An example would be to passed a private key to a Docker container with **openssl** installed to generate a certificate rather than using a local installed copy of **openssl**.

I've gone ahead and added the **neon-cli** `--insecure` option to disable the encrypted temp folder for the command and use the regular Windows temp folder instead.

**Comment by jefflill** [comment] 2019-05-14 15:34
@marcusbooyah: FYI: This change made it into the `0.4.6-alpha` release on the off-chance this was actually the issue.

**Comment by jefflill** [comment] 2019-05-24 22:55
@marcusbooyah: Is this still a problem?  Please close if not.

**Closed** 2019-05-24 23:09 UTC
